#!/bin/sh
if [ -n "$RSYNC_PROTOCOL" ] || [ -z "$SSH_TTY" ] || [ "$(uname -n)" != "meshify" ]; then
    exit 0
fi
sudo systemctl mask --runtime sleep.target suspend.target hibernate.target hybrid-sleep.target &>/dev/null
echo "Disabled sleep"

# sudo visudo:
# shh ALL=(ALL) NOPASSWD: /bin/systemctl mask --runtime sleep.target suspend.target hibernate.target hybrid-sleep.target
