default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-executables-have-shebangs
      - id: check-json
      - id: detect-private-key
  - repo: https://github.com/crate-ci/typos
    rev: 37bb98842b0d8c4ffebdb75301a13db0267cef89 # frozen: v1.47.2
    hooks:
      - id: typos
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95 # frozen: v0.11.0.1
    hooks:
      - id: shellcheck
        args: ["--exclude=SC1091,SC2181"]
        exclude: (zshrc|zsh)$
  - repo: https://github.com/hoxbro/prettier-pre-commit
    rev: df80de29d357cd4f5a116d1226eae3b8352271bd # frozen: v3.8.4
    hooks:
      - id: prettier
        types_or:
          - markdown
          - yaml
  - repo: https://github.com/hoxbro/taplo-pre-commit
    rev: 605f960c3c571f814f535622a688bcde63ee87f6 # frozen: v0.9.3
    hooks:
      - id: taplo
        args:
          [
            --option,
            align_comments=false,
            --option,
            column_width=100,
            --option,
            "indent_string=    ",
          ]
  - repo: https://github.com/johnnymorganz/stylua
    rev: 5ae6e7a55748414b4be30a832afd895014c65352 # frozen: v2.5.2
    hooks:
      - id: stylua-github
        name: stylua
        args: ["--config-path", ".config/stylua/stylua.toml"]
