general {
    lock_cmd = pidof hyprlock || (hyprlock && date "+%H:%M" >> /tmp/last-unlock)
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch "hl.dsp.dpms({ action = 'on' })"
}

listener {
    timeout = 150
    on-timeout = loginctl lock-session
}

listener {
    timeout = 180
    on-timeout = hyprctl dispatch "hl.dsp.dpms({ action = 'off' })"
    on-resume = hyprctl dispatch "hl.dsp.dpms({ action = 'on' })"
}
